In [1]:
#2D array

In [2]:
import numpy as np

In [3]:
b=[2,5,7,9,1]
c=[10,20,30,40,50]

In [4]:
a= np.array([b,c])

In [5]:
a

array([[ 2,  5,  7,  9,  1],
       [10, 20, 30, 40, 50]])

In [6]:
a.shape

(2, 5)

In [7]:
a.transpose()

array([[ 2, 10],
       [ 5, 20],
       [ 7, 30],
       [ 9, 40],
       [ 1, 50]])

In [8]:
a.reshape(5,2)

array([[ 2,  5],
       [ 7,  9],
       [ 1, 10],
       [20, 30],
       [40, 50]])

In [9]:
#Zeros

In [10]:
np.ones((6,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [13]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [14]:
#random

In [15]:
 np.random.randn(5)

array([ 0.62728755,  1.02856759, -0.48245272,  1.53297958, -0.19646206])

In [16]:
np.random.rand(4)

array([0.48238409, 0.44748255, 0.35560463, 0.39771171])

In [17]:
np.random.rand(5,5)

array([[0.68256494, 0.18483281, 0.40463132, 0.00788205, 0.39457364],
       [0.2616309 , 0.63524713, 0.91311947, 0.83741565, 0.97363251],
       [0.51677906, 0.06069164, 0.81780248, 0.00642253, 0.84674955],
       [0.78448411, 0.05504845, 0.28419464, 0.73096163, 0.55349179],
       [0.10666283, 0.09060256, 0.69954233, 0.85839539, 0.01914723]])

In [18]:
#Pandas

In [19]:
l10=[90,70,67,89,100]

In [20]:
import pandas as pd

In [21]:
exam=pd.Series(data=l10,index=['Alex','chinnu','yashu','harshu','preethi'])

In [22]:
exam

Alex        90
chinnu      70
yashu       67
harshu      89
preethi    100
dtype: int64

In [23]:
type(exam)

pandas.core.series.Series

In [24]:
exam2= pd.Series(data=[100,78,89,29,99],index=['harry','saatvik','yashu','harshu','dipta'])

In [25]:
result_1=exam+exam2

In [26]:
result_1

Alex         NaN
chinnu       NaN
dipta        NaN
harry        NaN
harshu     118.0
preethi      NaN
saatvik      NaN
yashu      156.0
dtype: float64

In [27]:
result_1.sum()

274.0

In [28]:
result_1.isnull().sum()

6

In [29]:
result_1.dropna()

harshu    118.0
yashu     156.0
dtype: float64

In [30]:
# array to series

In [31]:
d=np.array([45,90,135,180])

In [32]:
d

array([ 45,  90, 135, 180])

In [33]:
pd.Series(data=d)

0     45
1     90
2    135
3    180
dtype: int32

In [34]:
#Dictionary to series

In [35]:
result_1

Alex         NaN
chinnu       NaN
dipta        NaN
harry        NaN
harshu     118.0
preethi      NaN
saatvik      NaN
yashu      156.0
dtype: float64

In [36]:
result_1.fillna(result_1.mean())

Alex       137.0
chinnu     137.0
dipta      137.0
harry      137.0
harshu     118.0
preethi    137.0
saatvik    137.0
yashu      156.0
dtype: float64

In [37]:
#DataFrame

In [38]:
E=[[10,20,30,40,50],[11,22,33,44,55]]

In [39]:
pd.DataFrame(data=E,columns=['Alex','chinnu','harshu','Yashu','Preethi'],index=['Exam1','Exam2'])

Alex  chinnu  harshu  Yashu  Preethi
Exam1    10      20      30     40       50
Exam2    11      22      33     44       55

In [40]:
dict12={'Names':['Alex','chinnu','harshu','Yashu','Preethi'],
        'Exam1':[24,45,56,67,78],
        'Exam2':[34,56,78,90,np.nan]}

In [62]:
df=pd.DataFrame(data=dict12)

### head

In [43]:
df.head(2)

Names  Exam1  Exam2
0    Alex     24   34.0
1  chinnu     45   56.0

In [44]:
type(df['Names'])

pandas.core.series.Series

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
#tail

In [47]:
df.tail(2)

Names  Exam1  Exam2
3    Yashu     67   90.0
4  Preethi     78    NaN

In [48]:
df['Exam1']

0    24
1    45
2    56
3    67
4    78
Name: Exam1, dtype: int64

In [49]:
df.Exam1

0    24
1    45
2    56
3    67
4    78
Name: Exam1, dtype: int64

In [50]:
df['Exam1'].iloc[2]

56

In [51]:
df[['Exam1','Exam2']].iloc[1]

Exam1    45.0
Exam2    56.0
Name: 1, dtype: float64

In [52]:
df.isnull().sum()

Names    0
Exam1    0
Exam2    1
dtype: int64

In [53]:
df.dropna()

Names  Exam1  Exam2
0    Alex     24   34.0
1  chinnu     45   56.0
2  harshu     56   78.0
3   Yashu     67   90.0

In [54]:
df

Names  Exam1  Exam2
0     Alex     24   34.0
1   chinnu     45   56.0
2   harshu     56   78.0
3    Yashu     67   90.0
4  Preethi     78    NaN

In [55]:
#drop a column

In [56]:
df.drop(columns=['Exam2'])

Names  Exam1
0     Alex     24
1   chinnu     45
2   harshu     56
3    Yashu     67
4  Preethi     78

In [57]:
df

Names  Exam1  Exam2
0     Alex     24   34.0
1   chinnu     45   56.0
2   harshu     56   78.0
3    Yashu     67   90.0
4  Preethi     78    NaN

In [58]:
#filteration

In [59]:
df[df['Exam1']>50]['Names']

2     harshu
3      Yashu
4    Preethi
Name: Names, dtype: object

In [60]:
#Sorting

In [61]:
df.sort_values(by=['Exam1'],ascending=False)

Names  Exam1  Exam2
4  Preethi     78    NaN
3    Yashu     67   90.0
2   harshu     56   78.0
1   chinnu     45   56.0
0     Alex     24   34.0

In [63]:
df['Exam2'].sort_values(ascending=False)


3    90.0
2    78.0
1    56.0
0    34.0
4     NaN
Name: Exam2, dtype: float64